---
permalink: /blog/:categories/:year/:month/:day/:title.html
url: "https://fresco.buzhidao.net"
title: Fresco
tagline: 图片管理库
fbappid: "1615782811974223"
gacode: "UA-44373548-8"
relative_permalinks: false
description: >
  Fresco 是一个强大的图片加载组件。使用它之后，你不需要再去关心图片的加载和显示这些繁琐的事情！ 支持 Android 2.3(Gingerbread) 及后续版本。
timezone: Asia/Shanghai
ghrepo: "facebook/fresco"
ghrepo_doc: "Budaoshi/fresco-docs-cn"
logo: /static/logo.png

current_version: 1.11.0

support_library_version: 24.2.1

sync_time_at: 2019--03--01

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'rougeHighlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: :compressed

collections:
  docs:
    output: true
    permalink: /docs/:name/
  support:
    output: true
    permalink: /support/

color:
  primary: "#db6130"
  secondary: "#f9f9f9"
  # Use the following to specify whether the previous two colours are 'light'
  # or 'dark'
  primary-overlay: "dark"
  secondary-overlay: "light"

# Gems
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Set default open graph image for all pages
defaults:
  -
    scope:
      path: ""
    values:
      image: /static/og_image.png
